# Copyright (C) 2019, Fortishield Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds fortishield namespace to all resources.
namespace: fortishield

secretGenerator:
  - name: indexer-certs
    files:
      - certs/indexer_cluster/root-ca.pem
      - certs/indexer_cluster/node.pem
      - certs/indexer_cluster/node-key.pem
      - certs/indexer_cluster/dashboard.pem
      - certs/indexer_cluster/dashboard-key.pem
      - certs/indexer_cluster/admin.pem
      - certs/indexer_cluster/admin-key.pem
      - certs/indexer_cluster/filebeat.pem
      - certs/indexer_cluster/filebeat-key.pem
  - name: dashboard-certs
    files:
      - certs/dashboard_http/cert.pem
      - certs/dashboard_http/key.pem
      - certs/indexer_cluster/root-ca.pem

configMapGenerator:
  - name: indexer-conf
    files:
      - indexer_stack/fortishield-indexer/indexer_conf/opensearch.yml
      - indexer_stack/fortishield-indexer/indexer_conf/internal_users.yml
  - name: fortishield-conf
    files:
      - fortishield_managers/fortishield_conf/master.conf
      - fortishield_managers/fortishield_conf/worker.conf
  - name: dashboard-conf
    files:
      - indexer_stack/fortishield-dashboard/dashboard_conf/opensearch_dashboards.yml

resources:
  - base/fortishield-ns.yaml
  - base/storage-class.yaml

  - secrets/fortishield-api-cred-secret.yaml
  - secrets/fortishield-authd-pass-secret.yaml
  - secrets/fortishield-cluster-key-secret.yaml
  - secrets/dashboard-cred-secret.yaml
  - secrets/indexer-cred-secret.yaml

  - fortishield_managers/fortishield-cluster-svc.yaml
  - fortishield_managers/fortishield-master-svc.yaml
  - fortishield_managers/fortishield-workers-svc.yaml
  - fortishield_managers/fortishield-master-sts.yaml
  - fortishield_managers/fortishield-worker-sts.yaml

  - indexer_stack/fortishield-indexer/indexer-svc.yaml
  - indexer_stack/fortishield-indexer/cluster/indexer-api-svc.yaml
  - indexer_stack/fortishield-indexer/cluster/indexer-sts.yaml

  - indexer_stack/fortishield-dashboard/dashboard-svc.yaml
  - indexer_stack/fortishield-dashboard/dashboard-deploy.yaml
