# Copyright (C) 2019, Fortishield Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Indexer service: Communications

apiVersion: v1
kind: Service
metadata:
  name: fortishield-indexer
  namespace: fortishield
  labels:
    app: fortishield-indexer
spec:
  selector:
    app: fortishield-indexer
  ports:
    - name: indexer-nodes
      port: 9300
      targetPort: 9300
  clusterIP: None
