# Copyright (C) 2019, Fortishield Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Fortishield cluster Service: Manager nodes communication

apiVersion: v1
kind: Service
metadata:
  name: fortishield-cluster
  namespace: fortishield
  labels:
    app: fortishield-manager
spec:
  selector:
    app: fortishield-manager
  ports:
    - name: cluster
      port: 1516
      targetPort: 1516
  clusterIP: None
